exports.SUCCESS_PAYMENT_CODE = "OTS_0000";
exports.FAILED_PAYMENT_CODE = "OTS_0001";
exports.SUCCESS_PAYMENT_MSG = "PAYMENT_SUCCESSFUL";
exports.FAILED_PAYMENT_MSG = "PAYMENT_FAILED";

exports.ONLINE_PAYMENT = "ONLINE";
exports.OFFLINE_PAYMENT = "OFFLINE";

exports.REGISTRATION_SMS_TYPE = "REGISTRATION";

// these are status codes from payment gateway
exports.PG_SUCCESS_PAYMENT_CODE_1 = "OTS0000";
exports.PG_SUCCESS_PAYMENT_CODE_2 = "OTS0002";
